name: Route to Project

on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  route:
    name: Add item to project (optional)
    if: ${{ vars.GH_PROJECT_URL != '' && secrets.ADD_TO_PROJECT_PAT != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ vars.GH_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
